title: Travel Log
baseurl: "/travel-log" # the subpath of your site, e.g. /blog
twitter_username: vince_umo
github_username:  vinceumo

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - README.md
