baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Travel Log"
theme = "travel-log"

publishDir = "docs"

BaseURL = "travel-log"
canonifyurls = true

disableKinds = ["taxonomy","taxonomyTerm"]