---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/asia-south
  label: Asia south
  create: all
  match: "**/*"
- type: directory
  path: content/asia-southeast
  label: Asia southeast
  create: all
  match: "**/*"
- type: directory
  path: content/asia-east
  label: Asia east
  create: all
  match: "**/*"
- type: directory
  path: content/europe
  label: Europe
  create: all
  match: "**/*"
upload_dir: content
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.51'
