$('document').ready(function(){
    var destinations = [
        // {"country":"Brunei","city":"Bandar Seri Begawan"},
        // {"country":"Cambodia","city":"Siem Reap"},
        // {"country":"Cambodia","city":"Phnom Penh"},
        // {"country":"Cambodia","city":"Koh Samui"},
        // {"country":"Cambodia","city":"Kep"},
        // {"country":"China","city":"Shanghai"},
        // {"country":"China","city":"Yiwu"},
        // {"country":"Colombia","city":"Bogota"},
        // {"country":"Colombia","city":"Medellin"},
        // {"country":"Colombia","city":"Pandi"},
        // {"country":"Egypt","city":"Luxor"},
        // {"country":"Egypt","city":"Esna"},
        // {"country":"France","city":"Lyon"},
        // {"country":"France","city":"Paris"},
        // {"country":"France","city":"Bordeaux"},
        // {"country":"France","city":"Grenoble"},
        // {"country":"France","city":"Cholet"},
        // {"country":"France","city":"Palavas-Les-Flots"},
        // {"country":"France","city":"Corsica"},
        // {"country":"French Guana","city":"Cayenne"},
        // {"country":"French Guana","city":"Kuru"},
        // {"country":"Greece","city":"Athene"},
        //{"country":"Greece","city":"Rhodes"},
        //{"country":"Guadeloupe","city":"Guadeloupe"},
        //{"country":"Guatemala","city":"Antigua"},
        //{"country":"Guatemala","city":"Guatemala"},
        //{"country":"Guatemala","city":"Atitlan"},
        //{"country":"Guatemala","city":"Tikal"},
        //{"country":"India","city":"Delhi"},
        //{"country":"India","city":"Agra"},
        //{"country":"India","city":"Jaipur"},
        //{"country":"India","city":"Jaisalmer"},
        //{"country":"India","city":"Jodhpur"},
        // {"country":"India","city":"Udaipur"},
        // {"country":"India","city":"Pondicherry"},
        // {"country":"India","city":"Kochin"},
        // {"country":"India","city":"Gingee"},
        // {"country":"India","city":"Tanjor"},
        // {"country":"India","city":"Port Blair"},
        // {"country":"India","city":"Havelock"},
        // {"country":"Indonesia","city":"Jakarta"},
        // {"country":"Indonesia","city":"Yojakarta"},
        // {"country":"Indonesia","city":"Bromo"},
        // {"country":"Indonesia","city":"Ijen"},
        // {"country":"Indonesia","city":"Ubud"},
        // {"country":"Indonesia","city":"Gili"},
        // {"country":"Indonesia","city":"Kuta"},
        // {"country":"Indonesia","city":"Bima"},
        // {"country":"Indonesia","city":"Ende"},
        // {"country":"Indonesia","city":"Moni"},
        // {"country":"Indonesia","city":"Riong"},
        // {"country":"Indonesia","city":"Bajawa"},
        // {"country":"Indonesia","city":"Rinca"},
        // {"country":"Indonesia","city":"Seminyak"},
        // {"country":"Indonesia","city":"Nusa Lembongan"},
        // {"country":"Indonesia","city":"Amed"},
        // {"country":"Ireland","city":"Dublin"},
        // {"country":"Italy","city":"Turin"},
        // {"country":"Italy","city":"Milan"},
        // {"country":"Italy","city":"Venise"},
        // {"country":"Italy","city":"Rome"},
        // {"country":"Japan","city":"Tokyo"},
        // {"country":"Japan","city":"Nikko"},
        // {"country":"Japan","city":"Fuji"},
        // {"country":"Japan","city":"Kamakura"},
        // {"country":"Jordan","city":"Amman"},
        // {"country":"Jordan","city":"Petra"},
        // {"country":"Jordan","city":"Wadi Rum"},
        // {"country":"Jordan","city":"Deadsea"},
        // {"country":"Kenya","city":"Nairobi"},
        // {"country":"Kenya","city":"Mombasa"},
        // {"country":"Kenya","city":"Nakuru"},
        // {"country":"Kenya","city":"Masaimara"},
        // {"country":"Laos","city":"Luang Prabang"},
        // {"country":"Laos","city":"Vientiane"},
        // {"country":"Laos","city":"Si Phan Don"},
        // {"country":"Laos","city":"Huay Xai"},
        // {"country":"Malaysia","city":"Kuching"},
        // {"country":"Malaysia","city":"Melaka"},
        // {"country":"Malaysia","city":"Kuala Lumpur"},
        // {"country":"Malaysia","city":"Penang"},
        // {"country":"Marocco","city":"Marrakech"},
        // {"country":"Marocco","city":"Essaouira"},
        // {"country":"Marocco","city":"Tanger"},
        // {"country":"Marocco","city":"Ceuta"},
        // {"country":"Marocco","city":"Ouarzazate"},
        // {"country":"Marocco","city":"Rabat"},
        // {"country":"Maurice","city":"Maurice"},
        // {"country":"Mexico","city":"Cancun"},
        // {"country":"Mexico","city":"Chichen Itza"},
        // {"country":"Myanmar","city":"Yangon"},
        // {"country":"Myanmar","city":"Mawlamyine"},
        // {"country":"Myanmar","city":"Bagan"},
        // {"country":"Myanmar","city":"Kalaw"},
        // {"country":"Myanmar","city":"Inle"},
        // {"country":"Philippines","city":"Manila"},
        // {"country":"Philippines","city":"Cebu city"},
        // {"country":"Philippines","city":"Alona beach, Bohol"},
        // {"country":"Philippines","city":"Sabang, Palawan"},
        // {"country":"Philippines","city":"El Nido, Palawan"},
        // {"country":"Philippines","city":"Coron Town"},
        // {"country":"Philippines","city":"Tagaytay"},
        // {"country":"Philippines","city":"Puerto Galera"},
        // {"country":"Seychelle","city":"Seychelle"},
        // {"country":"Singapore","city":"Singapore"},
        // {"country":"Spain","city":"Barcelona"},
        // {"country":"Sri Lanka","city":"Colombo"},
        // {"country":"Sri Lanka","city":"Unawatuna"},
        // {"country":"Sri Lanka","city":"Mirisa"},
        // {"country":"Sri Lanka","city":"Ella"},
        // {"country":"Sri Lanka","city":"Nuwara Elyia "},
        // {"country":"Sri Lanka","city":"Sigiryia"},
        // {"country":"Sri Lanka","city":"Polonnaruwa"},
        // {"country":"Sri Lanka","city":"Arugam Bay "},
        // {"country":"Sri Lanka","city":"Hatton"},
        // {"country":"Switzerland","city":"Geneva"},
        // {"country":"Thailand","city":"Koh Chang"},
        // {"country":"Thailand","city":"Chiang Mai"},
        // {"country":"Thailand","city":"Pai"},
        // {"country":"Thailand","city":"Bangkok"},
        // {"country":"Thailand","city":"Ayutthaya"},
        // {"country":"Thailand","city":"Chiang Rai"},
        // {"country":"Uk","city":"London"},
        // {"country":"Uk","city":"Oxford"},
        // {"country":"Uk","city":"Cambridge"},
        // {"country":"Uk","city":"Brighton"},
        // {"country":"Uk","city":"Bath"},
        // {"country":"Uk","city":"Stratford"},
        // {"country":"Uk","city":"Liverpool"},
        // {"country":"Uk","city":"Manchester"},
        // {"country":"Uk","city":"Chester"},
        // {"country":"Uk","city":"Blackpool"},
        // {"country":"Usa","city":"New York"},
        // {"country":"Usa","city":"Los Angeles"},
        // {"country":"Usa","city":"San Francisco"},
        // {"country":"Usa","city":"Las Vegas"},
        // {"country":"Usa","city":"Death Valley"},
        // {"country":"Usa","city":"Monument Valley"},
        // {"country":"Venezuela","city":"Caracas"},
        // {"country":"Venezuela","city":"Ciudad Bolivar"},
        // {"country":"Venezuela","city":"Tepui"},
        // {"country":"Venezuela","city":"Canaima"},
        // {"country":"Venezuela","city":"Orinoco"},
        {"country":"Vietnam","city":"Hanoi"},
        {"country":"Vietnam","city":"Saigon"},
        {"country":"Vietnam","city":"Mui Ne"},
        {"country":"Vietnam","city":"Halong Bay"},
        {"country":"Vietnam","city":"Ninh Binh"},
        {"country":"Vietnam","city":"Cantho"},
        {"country":"Vietnam","city":"Chaudoc"},
        {"country":"Vietnam","city":"Hoi An"},
        {"country":"Vietnam","city":"Hue"},
        {"country":"Vietnam","city":"Danang"},
        {"country":"Philippines","city":"Manila"}
        ];

    for(var i=0; i <= destinations.length; i++){
        var city = destinations[i].city;
        var country = destinations[i].country;
        getLocation(city, country);
    };

    function getLocation(city, country){
        var geocoder =  new google.maps.Geocoder();
        geocoder.geocode( { 'address': city +', '+ country}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                var location =  results[0].geometry.location.lat() + ', ' + results[0].geometry.location.lng();
                $('.getlocationtable').append('<tr><td>'+ country + '</td><td>' + city + '</td><td>' + location + '</td></tr>');
                console.log(location);
            } else {
                $('.getlocationtable').append('<tr><td>'+ country + '</td><td>' + city + '</td><td>' + status + '</td></tr>');
            }
        });
    }
});
